src/main/java/com/my/attendance/dao/AttendanceRepository.java, src/main/java/com/my/attendance/dto/AttendanceDTO.java, src/main/java/com/my/attendance/entity/AttendanceEntity.java, src/main/java/com/my/attendance/service/AttendanceService.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/chat/entity/ChatRoomEntity.java, src/main/java/com/my/chat/entity/MessageEntity.java, src/main/java/com/my/department/entity/DepartmentEntity.java, src/main/java/com/my/member/entity/MemberEntity.java, src/main/resources/db.properties
=> [feat] entity 연관관계 설정

src/main/java/com/my/attendance/entity/AttendanceEntity.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/notification/dto/NotificationDTO.java, src/main/java/com/my/notification/entity/NotificationEntity.java
=> [Feat] notification entity 및 dto 수정

src/main/java/com/my/attendance/control/AttendanceController.java, src/main/java/com/my/attendance/dto/AttendanceDTO.java, src/main/java/com/my/attendance/entity/AttendanceEntity.java, src/main/java/com/my/attendance/service/AttendanceMapper.java, src/main/java/com/my/attendance/service/AttendanceService.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/attendance/service/AttendanceStatus.java, src/main/java/com/my/attendance/service/AttendanceTime.java, src/main/java/com/my/member/entity/MemberEntity.java
[feat] controller 추가 및 데이터 전달 테스트 완료
=> [feat] controller 추가 및 데이터 전달 테스트 완료

src/main/java/com/my/attendance/entity/AttendanceEntity.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/car/entity/CarEntity.java, src/main/java/com/my/car/entity/CarRentEntity.java, src/main/java/com/my/chat/entity/ChatRoomEntity.java, src/main/java/com/my/chat/entity/MessageEntity.java, src/main/java/com/my/department/entity/DepartmentEntity.java, src/main/java/com/my/meetingroom/entity/MeetingReservationEntity.java, src/main/java/com/my/meetingroom/entity/MeetingroomDetailEntity.java, src/main/java/com/my/meetingroom/entity/ParticipantsEntity.java, src/main/java/com/my/meetingroom/repository/MeetingroomRepository.java, src/main/java/com/my/notice/entity/NoticeEntity.java, src/main/java/com/my/notification/entity/NotificationEntity.java, src/main/java/com/my/schedule/entity/ScheduleEntity.java
=> [feat] entitiy 컬럼 수정!

src/main/java/com/my/address/controller/AddressController.java, src/main/java/com/my/address/dto/AddressMemberDTO.java, src/main/java/com/my/address/service/AddressService.java, src/main/java/com/my/address/service/AddressServiceImpl.java, src/main/java/com/my/login/controller/LoginController.java, src/main/java/com/my/login/dto/LoginRequestDTO.java, src/main/java/com/my/login/service/LoginService.java, src/main/java/com/my/login/service/LoginServiceImpl.java, src/main/java/com/my/member/dto/MemberDTO.java, src/main/java/com/my/member/entity/MemberEntity.java, src/main/java/com/my/member/repository/MemberRepository.java
=> Feat address

src/main/java/com/my/attendance/control/AttendanceController.java, src/main/java/com/my/attendance/dao/AttendanceRepository.java, src/main/java/com/my/attendance/dto/AttendanceDTO.java, src/main/java/com/my/attendance/entity/AttendanceEntity.java, src/main/java/com/my/attendance/service/AttendanceMapper.java, src/main/java/com/my/attendance/service/AttendanceService.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/member/entity/MemberEntity.java, src/main/java/com/my/member/repository/MemberRepository.java
[feat] attendance find, create, update 메서드
=> [feat] attendance find, create, update 메서드

src/main/java/com/my/attendance/control/AttendanceController.java, src/main/java/com/my/attendance/dao/AttendanceRepository.java, src/main/java/com/my/attendance/dto/AttendanceDTO.java, src/main/java/com/my/attendance/entity/AttendanceEntity.java, src/main/java/com/my/attendance/service/AttendanceMapper.java, src/main/java/com/my/attendance/service/AttendanceService.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java
=> [feat] attendance 페이징 처리 완료

src/main/java/com/my/attendance/control/AttendanceController.java, src/main/java/com/my/attendance/dao/AttendanceRepository.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/attendance/service/AttendanceTime.java
=> [DOCS] attendance 주석 삭제 및 정리

src/main/java/com/my/attendance/dao/AttendanceRepository.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java
=> [feat] 출근 및 퇴근 유효성검사 완료

src/main/java/com/my/attendance/dao/AttendanceRepository.java, src/main/java/com/my/attendance/dto/AttendanceDTO.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/attendance/service/AttendanceStatus.java, src/main/java/com/my/notification/control/NotificationController.java, src/main/java/com/my/notification/dao/EmitterRepository.java, src/main/java/com/my/notification/dao/EmitterRepositoryImpl.java, src/main/java/com/my/notification/dao/NotificationRepository.java, src/main/java/com/my/notification/dto/NotificationDTO.java, src/main/java/com/my/notification/entity/NotificationEntity.java, src/main/java/com/my/notification/service/NotificationService.java, src/main/java/com/my/notification/service/NotificationServiceImpl.java
=> [DOCS] attendance 수정2

src/main/java/com/my/chat/controller/ChatController.java, src/main/java/com/my/chat/controller/ChatRoomController.java, src/main/resources/db.properties
=> [Fix] git test

src/main/java/com/my/notification/control/NotificationController.java, src/main/resources/db.properties
=> Feat notificati[feat] 회의실 예약 구현중

src/main/java/com/my/meetingroom/service/MeetingroomServiceImpl.java, src/main/java/com/my/notification/service/NotificationService.java, src/main/java/com/my/notification/service/NotificationServiceImpl.java
=> [feat] 회의실 예약 참여자 모두에게 전송 완료

src/main/java/com/my/login/controller/LoginController.java, src/main/java/com/my/meetingroom/service/MeetingroomMapper.java, src/main/java/com/my/meetingroom/service/MeetingroomServiceImpl.java, src/main/java/com/my/notification/control/NotificationController.java, src/main/java/com/my/notification/dto/NotificationDTO.java, src/main/java/com/my/notification/entity/NotificationEntity.java, src/main/java/com/my/notification/service/NotificationServiceImpl.java
=> [feat] 회의실 예약 시간표시

src/main/java/com/my/notification/control/NotificationController.java, src/main/java/com/my/notification/service/NotificationService.java, src/main/java/com/my/notification/service/NotificationServiceImpl.java
=> [feat] 알림삭제 기능 구현

src/main/java/com/my/chat/controller/ChatController.java, src/main/java/com/my/chat/controller/ChatRoomController.java, src/main/java/com/my/chat/pubsub/RedisSubscriber.java, src/main/java/com/my/chat/service/ChatService.java
=> [Feat] 채팅 controller, config 파일 수정

src/main/java/com/my/attendance/control/AttendanceController.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/meetingroom/control/MeetingroomController.java, src/main/resources/db.properties
=> [feat] 내림차순 정렬

src/main/java/com/my/meetingroom/service/MeetingroomServiceImpl.java, src/main/java/com/my/notification/service/NotificationServiceImpl.java, src/main/java/com/my/stuff/service/StuffReqServiceImpl.java, src/main/resources/db.properties
[DOCS] 회의실 예약자 및 참여자에게 알림 보내는 코드 사라져서 추가
=> [DOCS] 회의실 예약자 및 참여자에게 알림 보내는 코드 사라져서 추가

src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/attendance/service/AttendanceStatus.java, src/main/java/com/my/attendance/service/AttendanceTime.java, src/main/java/com/my/config/AttendanceConfig.java, src/main/resources/application.properties
=> [feat] 근태 상태, 시간 외부설정파일로 변경

src/main/java/com/my/attendance/control/AttendanceController.java, src/main/java/com/my/attendance/dao/AttendanceRepository.java, src/main/java/com/my/attendance/service/AttendanceService.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java
[feat] 메인 현재시간, 퇴근시간 출력 메서드 추가
=> [feat] 메인 현재시간, 퇴근시간 출력 메서드 추가Feat notification

src/main/java/com/my/attendance/service/AttendanceService.java, src/main/java/com/my/notification/dto/NotificationDTO.java, src/main/resources/db.properties
[feat] notification dto 수정(type 추가)
=> [feat] notification dto 수정(type 추가)

src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/car/control/CarController.java, src/main/java/com/my/config/SchedulerConfig.java, src/main/java/com/my/meetingroom/service/ReservationScheduler.java, src/main/java/com/my/notification/control/NotificationController.java, src/main/java/com/my/notification/entity/NotificationEntity.java, src/main/java/com/my/notification/service/NotificationServiceImpl.java, src/main/resources/application.properties, src/main/resources/db.properties, src/test/java/com/my/test/StuffReqTest.java
=> [DOCS] 30분전 알림 수정중

src/main/java/com/my/attendance/control/AttendanceController.java, src/main/java/com/my/attendance/service/AttendanceService.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/java/com/my/meetingroom/service/ReservationScheduler.java
=> [feat] 출근 및 근태 완료!

src/main/java/com/my/attendance/dao/AttendanceRepository.java, src/main/java/com/my/attendance/entity/AttendanceEntity.java, src/main/java/com/my/attendance/service/AttendanceServiceImpl.java, src/main/resources/application.properties
=> [feat] 근태 상태 변경

src/main/java/com/my/meetingroom/service/MeetingroomMapper.java, src/main/java/com/my/meetingroom/service/MeetingroomServiceImpl.java
=> [feat] 회의실 단체 알림 수정

src/main/java/com/my/attendance/service/AttendanceServiceImpl.java
=> [feat] 알림 페이지이동 및 삭제 수정
